#!/bin/zsh

################################################################################
#   General
################################################################################

autoload -Uz compinit && compinit -i
autoload -U colors && colors

export EDITOR='nvim'
export TERM='st'
export ATHAME_ENABLED=0

# Proper less config
LESS='--quit-if-one-screen --ignore-case --status-column --LONG-PROMPT'
LESS="$LESS --RAW-CONTROL-CHARS --HILITE-UNREAD --tabs=4 --no-init --window=-4"
LESS="$LESS --mouse --wheel-lines=1"
export LESS=$LESS


################################################################################
#   Completions
################################################################################

fpath=($ZDOTDIR/completion/git/ $fpath)


################################################################################
#   Global plugins
################################################################################

GLOBAL_PLUGINS=/usr/share/

# vi-mode
source $GLOBAL_PLUGINS/zsh/plugins/zsh-vi-mode/zsh-vi-mode.plugin.zsh
ZVM_VI_HIGHLIGHT_BACKGROUND=fg=white
ZVM_VI_SURROUND_BINDKEY="s-prefix"
ZVM_INSERT_MODE_CURSOR="\033[2 q"
ZVM_NORMAL_MODE_CURSOR="\033[4 q"
ZVM_NORMAL_MODE_CURSOR="\033[4 q"

# fzf
FZF_DEFAULT_OPTS='
    --color=bg+:#282c34,bg:#282c34,spinner:#c678dd,hl:#be5046
    --color=fg:#abb2bf,header:#586e75,info:#d19a66,pointer:#98c379
    --color=marker:#e5c07b,fg+:#abb2bf,prompt:#d19a66,hl+:#be5046
'
source $GLOBAL_PLUGINS/fzf/completion.zsh
source $GLOBAL_PLUGINS/fzf/key-bindings.zsh
zvm_after_init_commands+=("source $GLOBAL_PLUGINS/fzf/key-bindings.zsh")

# syntax-highlighting
source $GLOBAL_PLUGINS/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
ZSH_HIGHLIGHT_STYLES[suffix-alias]=fg=white
ZSH_HIGHLIGHT_STYLES[precommand]=fg=white
ZSH_HIGHLIGHT_STYLES[arg0]=fg=white
ZSH_HIGHLIGHT_STYLES[path]=none
ZSH_HIGHLIGHT_STYLES[path_prefix]=none
ZSH_HIGHLIGHT_STYLES[single-hyphen-option]=fg=yellow
ZSH_HIGHLIGHT_STYLES[double-hyphen-option]=fg=yellow
ZSH_HIGHLIGHT_STYLES[single-quoted-argument]=fg=green
ZSH_HIGHLIGHT_STYLES[double-quoted-argument]=fg=green

# auto-suggest
source $GLOBAL_PLUGINS/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=#5c6370"
ZSH_AUTOSUGGEST_USE_ASYNC=1

# git-status
source $GLOBAL_PLUGINS/gitstatus/gitstatus.plugin.zsh


################################################################################
#   Local plugins
################################################################################

LOCAL_PLUGINS=$ZDOTDIR/plugins/

source $LOCAL_PLUGINS/history.zsh
source $LOCAL_PLUGINS/autocomplete.zsh
source $LOCAL_PLUGINS/keybindings.zsh
zvm_after_init_commands+=("source $LOCAL_PLUGINS/keybindings.zsh")
source $LOCAL_PLUGINS/aliases.zsh
source $LOCAL_PLUGINS/colored-man-pages.zsh


################################################################################
#   Theme
################################################################################

THEMES=$ZDOTDIR/themes
source $THEMES/bloodhail.zsh-theme
