#!/bin/bash

connection_type=$1

# Find interfaces
for dev in `ls /sys/class/net`; do
    [[ -d /sys/class/net/$dev/wireless ]] && wifi=$dev || \
        { [[ $dev != 'lo' ]] && eth=$dev; }
done

# Set interface
[[ -n $wifi && $connection_type == 'wireless' ]] && interface=$wifi ||
    { [[ -n $eth && $connection_type == 'wired' ]] && interface=$eth || exit; }

# Spoof
ip link set $interface down
macchanger -A $interface
ip link set $interface up
