#!/bin/bash

case $BLOCK_BUTTON in
    1|2|3) ~/.config/i3/scripts/i3blocks/interactivebar date-bar </dev/null &>/dev/null & ;;
esac

date "+ $date_icon %d/%m   $clock_icon %H:%M  " && echo && echo $color
