#!/bin/python

import sys
import subprocess

import tty
import termios

import colorama
from colorama import Fore
colorama.init(autoreset=True)


def get_char():
    fd = sys.stdin.fileno()
    oldSettings = termios.tcgetattr(fd)
    try:
        tty.setcbreak(fd)
        answer = sys.stdin.read(1)
    finally:
        termios.tcsetattr(fd, termios.TCSADRAIN, oldSettings)

    return answer


def get_updates():
    output = ''
    try:
        output = subprocess.check_output(['checkupdates+aur']).decode('utf-8')
    except subprocess.CalledProcessError as exc:
        # checkupdates exits with 2 and no output if no updates are available.
        # we ignore this case and go on
        if not (exc.returncode == 2 and not exc.output):
            raise exc

    if not output:
        return []

    updates = [line.split(' ') for line in output.split('\n') if line]
    return updates


if __name__ == '__main__':
    print("\033[?25l" + Fore.YELLOW + 'Fetching...', end='\r')
    updates = get_updates()
    for update in updates:
        for idx, item in enumerate(update):
            if idx == 0:
                print(colorama.Style.BRIGHT + Fore.BLUE + item, end='  ')
            elif idx == 1:
                print(Fore.RED + item, end=' ')
            elif idx == 2:
                print(item, end=' ')
            elif idx == 3:
                print(Fore.GREEN + item, end=' ')
            else:
                print(item, end=' ')
        print()

    print(67*'-')
    print(Fore.YELLOW + str(len(updates)) + ' updates available', end='')
    get_char()
