#!/bin/bash

case "$BLOCK_BUTTON" in
    1|2|3) ~/.config/i3/scripts/i3blocks/interactivebar updates-bar </dev/null &>/dev/null &
          echo $icon && echo && echo $color ;
          exit ;;
esac

updates=$(checkupdates+aur | wc -l)
[[ $updates -gt 0 ]] && echo $icon && echo && echo $color
