#!/bin/bash

case $BLOCK_BUTTON in
    1|3) ~/.config/i3/scripts/i3blocks/interactivebar volume-bar </dev/null &>/dev/null &;;
    2) amixer -q -D pulse sset Master toggle ;;
    4) amixer -q -D pulse sset Master 10%- ;;
    5) amixer -q -D pulse sset Master 10%+ unmute ;;
esac

vol=$(ponymix | grep sink -A 2 | grep Volume | cut -c 16-)
muted=$(echo $vol | sed 's/^.*%\s//g')

if [[ $muted == '[Muted]' ]]; then
    color=$mute_color
    vol=$(echo $vol | cut -c -3)
fi

num=$(echo $vol | sed 's/%//g')

[[ $muted != '[Muted]' && $num -gt 100 ]] || over_color=$color

for i in {1..10}; do
    [[ $num -le 100 ]] && \
        { [[ $num -lt $(($i*10)) ]] && bars=$bars"-" || bars=$bars'|'; } || \
        { [[ $(($i*10)) -le $(($num - 100)) ]] && over=$over'|' || bars=$bars'|'; }
done

text_icon="<span color='$color' size='large'>$icon</span>"
text_bars="<span color='$color' size='x-small' rise='3000'>$bars</span>"
text_over="<span color='$over_color' size='x-small' rise='3000'>$over</span>"

# echo $text_icon $text_over$text_bars
echo $text_icon $text_bars$text_over
