#!/bin/bash

cards=$(pacmd list-cards | grep 'output:' \
                         | sed '/active profile:/d' \
                         | sed '/available: no/d' \
                         | awk '{ print $1 }' \
                         | sed 's/.$//')

names=$(pacmd list-cards | grep 'output:' \
                         | sed '/active profile:/d' \
                         | sed '/available: no/d' \
                         | cut -f 2- -d ' ' \
                         | sed "s/([^)]*)//g")

choices="$names\nManual selection"
chosen=$(echo -e "$choices" | dmenu -i -b -nb '#282C34' \
                                          -nf '#ABB2BF' \
                                          -sb '#98c379' \
                                          -sf '#191919' \
                                          -fn 'Ubuntu:pixelsize=17')

chosen=$(echo $chosen | xargs)
case "$chosen" in
    "Manual selection") st -n volume-bar -e ncpamixer ;;
    *)  while read n <&3 && read c <&4; do
            [[ "$chosen" == "$n" ]] && pacmd set-card-profile 0 $c
        done 3<<<"$names" 4<<<"$cards" ;;
esac
