#!/bin/sh

choices="laptop\nHDMI\nChange sink\nManual selection"
chosen=$(echo -e "$choices" | dmenu -i -b -nb '#282C34' \
                                          -nf '#ABB2BF' \
                                          -sb '#98c379' \
                                          -sf '#191919' \
                                          -fn 'Ubuntu:pixelsize=17')

case "$chosen" in
    laptop) pacmd set-card-profile 0 "output:analog-stereo+input:analog-stereo" ;;
    HDMI) pacmd set-card-profile 0 "output:hdmi-stereo-extra1" ;;
    "Change Sink") ~/.config/i3/scripts/changesink ;;
    "Manual selection") st -n volume-bar -e ncpamixer ;;
esac
