#!/bin/sh

BLANK='#00000000'
CLEAR='#ffffff22'
DEFAULT='#5c6370ff'
TEXT='#abb2bfff'
WRONG='#be5046ff'
VERIFYING='#c678ddff'

[ -n "$(pgrep i3lock)" ] && exit

i3lock --color=$BLANK \
       --insidever-color=$CLEAR \
       --ringver-color=$VERIFYING \
       --insidewrong-color=$CLEAR \
       --ringwrong-color=$WRONG \
       --inside-color=$BLANK \
       --ring-color=$DEFAULT \
       --line-color=$BLANK \
       --separator-color=$DEFAULT \
       --verif-color=$TEXT \
       --wrong-color=$TEXT \
       --time-color=$TEXT \
       --date-color=$TEXT \
       --layout-color=$TEXT \
       --keyhl-color=$WRONG \
       --bshl-color=$WRONG \
       --screen 2 \
       --blur 1 \
       --clock \
       --indicator \
       --time-str="%H:%M:%S" \
       --date-str="%A, %m %Y" \
       -n
