#!/bin/bash

help() {
    echo 'Usage: video2gif video.mkv'
    echo
    echo '  Converting videos to gifs using palettegen.'
}

[[ -z $1 || $1 = '--help' || $1 = '-h' ]] && help && exit

for arg in $@; do
    file=$arg

    base="$(basename -- $file)"
    name="./${base%.*}"

    ffmpeg -i $file -vf palettegen $name.png && \
        ffmpeg -i $file -i $name.png -filter_complex paletteuse $name.gif && \
        rm $name.png
done
